apiVersion: apps/v1
kind: Deployment
metadata:
  name: sa-api
  labels:
    app: sa-api
spec:
  selector:
    matchLabels:
      app: sa-api
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1 
  template:
    metadata:
      labels:
        app: sa-api
    spec:
      containers:
      - image: binhtran240297/sa-api
        imagePullPolicy: Always
        name: sa-api
        env:
          - name: SA_LOGIC_API_URL
            value: "http://sa-logic"
        ports:
          - containerPort: 8080